### PR TITLE
feat: Rofi google search

### PR DESCRIPTION
**Pull request by rubiin**
Adds a rofi search for searching for things in google

### CODE REVIEW

**Comment by rubiin** [comment]
Its bare bones , might need to theme

**Comment by kRHYME7** [comment]
Will also try to  support other Search Engines. 

Some uses duckduckgo . 


IIRC,  I forgot the search engine but  I want to rewrite this into like that. 
So what it does is when I input ` g: some  amazing hacks `   it searches in google because I prefix ` g: `  , and so on. I think this would be cool.

**Comment by rubiin** [comment]
yeah prefix sounds like a nice idea

**Review by kRHYME7 — COMMENTED** [review]
I forgot to tell you This will break the parsing, lol

**Comment by rubiin** [comment]
works nice;

bindl = $mainMod, B, exec, Hyde show search  # launch search


Also , I had named the label as google search you have to rename it to internet search here 
https://github.com/kRHYME7/Hyde-cli/blob/f02aaee1743c32309880134a63665b410dc17a3e/Hyde#L734

**Pull request merged**
