### PR TITLE
feat(screenshot): upload screenshot

### PR DESCRIPTION
**Pull request by rubiin**
Adds a script that can upload the screenshot taken.
The best place to invoke the script is to add it here 
https://github.com/kRHYME7/Hyde-cli/blob/9a94ab16f9134fe63d40dc3cf86bfaec2f0a65a8/Hyde#L770

Maybe a ` --share` option ?

Also note this introduces a new dep pngquant which is a image compression

### CODE REVIEW

**Comment by rubiin** [comment]
demo : 
image

**Comment by kRHYME7** [comment]
Will try to find alternative, this actually gives 2 dependencies. insert 'yad '

**Comment by rubiin** [comment]
yad was already there on my system . Just had to install pngnaut

**Comment by kRHYME7** [comment]
what is the use of pngnaut BTW ?

**Comment by rubiin** [comment]
> what is the use of pngnaut BTW ?

image compression.

`whiptail --msgbox "my text" 10 20` for dialog you can replace with this. This is native

**Comment by rubiin** [comment]
I think we can remove that too. Will refactor

**Comment by kRHYME7** [comment]
for image comp/decomp we can use imagemagick

**Comment by kRHYME7** [comment]
WAhhhh what package brought whiptail ?? I got it too

**Comment by rubiin** [comment]
whiptail is native terminal dialog

**Comment by rubiin** [comment]
okay removed both dep. Thanks chatgpt :D

**Comment by kRHYME7** [comment]
@rubiin  Yow I got something for yah. 

image

You can play around with notify send plus rofi. 
Here's the basic idea ` ❯ notify-send "upload online??" --action="okokoko" --action="command to do so " --action="alright" `

**Comment by rubiin** [comment]
@kRHYME7 any updates on this. I am thinking of adding a font switcher afterwards for Hyde. Will switch fonts for kitty, code and maybe waybar

**Comment by kRHYME7** [comment]
> You can play around with notify send plus rofi.
Here's the basic idea ❯ notify-send "upload online??" --action="okokoko" --action="command to do so " --action="alright"

I think we can harness 

The notification prompt for this. 

Will merge this later but maybe I'll change it.

**Comment by rubiin** [comment]
> > You can play around with notify send plus rofi.
> > Here's the basic idea ❯ notify-send "upload online??" --action="okokoko" --action="command to do so " --action="alright"
> 
> I think we can harness
> 
> The notification prompt for this.
> 
> Will merge this later but maybe I'll change it.

What do you think about the font change?

**Comment by kRHYME7** [comment]
> What do you think about the font change?
That would be cool! 


Are you trying to do text manipulation for each config files?

**Comment by rubiin** [comment]
yeah I already have local script tailored for my needs , thoiught i should share
Its inspired from https://github.com/basecamp/omakub/blob/master/bin/omakub-font

**Comment by kRHYME7** [comment]
Wow, sure! I'll probably check this out.

**Comment by kRHYME7** [comment]
>  Its inspired from https://github.com/basecamp/omakub/blob/master/bin/omakub-font

You can use this to list the fonts beautifully `   fc-list --format="%{family[0]}\n" | sort | uniq `

**Review by kRHYME7 — APPROVED** [review]
Will do some revisions later

**Comment by rubiin** [comment]
Do merge the release PR when you are done with the revisions

**Pull request merged**
