### PR TITLE
fix: and add faq

### PR DESCRIPTION
**Pull request by rubiin**
Spell errors and some small fixes here and there

### CODE REVIEW

**Comment by kRHYME7** [comment]
why remove the USAGE?

**Comment by rubiin** [comment]
We don't need a usage doc as we sort of have a manpage .
But thats upto you , will remove that from commit

**Comment by rubiin** [comment]
For now I have just kept the readme changes

**Comment by kRHYME7** [comment]
But we don't have a manual page  online. Will keep the USAGE for now. I'm thinking of auto generating this as .md file.

**Review by kRHYME7 — APPROVED** [review]
🙏

**Comment by rubiin** [comment]
Could you also check my another PR. with theme patch the selector was overlapping with the text. I also made all selectors generic as possible

**Comment by kRHYME7** [comment]
oh yeah I'm lil Busy these days. I will try to test it on my system later.

**Comment by rubiin** [comment]
sure thing . I attached a screenshot so its easier to review

**Pull request merged**
