### PR TITLE
feat: list packages and there versions

### PR DESCRIPTION
**Pull request by rubiin**
Just a small feature that will help users with some debug input while submitting issues

### CODE REVIEW

**Comment by kRHYME7** [comment]
Great!

**Review by kRHYME7 — APPROVED** [review]
This should be inside ` Hyde check [] ` 

Let me do it later. Thanks!

**Comment by rubiin** [comment]
image
similar to this

**Comment by rubiin** [comment]
looking good for first version 
image

**Comment by kRHYME7** [comment]
Will this be neat and fair if we add this to ` Hyde check Package ` ? 

image


We already have ` Hyde systeminfo ` which spits the version plus the git commit that is currently in their .configs. Also the hyprland version. Will push something later, feel free to open issue for suggestions. 

image


BTW reminder, if you want to access the clone directory, you first need to invoke ` navigate_clone `.

**Comment by rubiin** [comment]
Hyde check Package looks fine . Thats what we are doing anyways so looks sensible , go for it

**Comment by rubiin** [comment]
It would be great if people submitting issues on hyprdots start posting a screenshot of the output as it will be lot easier to debug

**Comment by kRHYME7** [comment]
True !  we can tell them to get the output for  ` Hyde systeminfo ` 


something like this 

**Hyde-cli version:**
Version: v0.5.2-129-gd8ad308
Last commit: d8ad308 Thu May 16 22:48:10 2024 +0800
Commit message: 'Merge pull request #57 from rubiin/feat/info  feat: list packages and there versions'

**Hyde repository:**
CloneDirectory: /home/khing/.cache/hyde/Hyde-Clone
Git URL: https://github.com/prasanthrangan/hyprdots
Git Branch: main
Hyde version: v0.1.0.r67.29b199a
Modified:  Sun May 12 11:26:22 2024 -0700
Commit message: fix: use same emoji icon for indication cpu and gpu temps (#1491)

Now cpu temp string uses same icons as gpu. Taken from gpuinfo.sh:143

**Hyprland system information:** (hyprctl)
Hyprland, built from branch main at commit 33a7b7bb6b307d6e4a093f75ffdda0419cd7ffaf  (core: fix on-empty workspace being called too often (6026)).
Date: Sun May 12 01:03:32 2024
Tag: v0.40.0-65-g33a7b7bb, commits: 4671

flags: (if any)


System Information:
System name: Linux
Node name: archlinux
Release: 6.8.9-zen1-2-zen
Version: #1 ZEN SMP PREEMPT_DYNAMIC Tue, 07 May 2024 22:06:02 +0000


GPU information: 
00:02.0 VGA compatible controller [0300]: Intel Corporation CometLake-U GT2 [UHD Graphics] [8086:9b41] (rev 02) (prog-if 00 [VGA controller])


os-release: NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://gitlab.archlinux.org/groups/archlinux/-/issues"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo


plugins:

**Pull request merged**
